version: '3.8'

services:
    api-server:
      container_name: api-server
      build: ./
      ports:
        - 8080:8080
      depends_on:
        - database

    database:
      container_name: database
      build: ./postgres/
      restart: always
      image: postgres:latest
#      volumes:
#        - ./.database/postgres/data:/var/lib/postgresql/data
      env_file:
        - .env
#      environment:
#        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#        - POSTGRES_USER:${POSTGRES_USER}
      ports:
        - 5434:5432