version: '3.8'

services:
    api-server:
      container_name: api-server
      build: ./
      ports:
        - 8080:8080
      depends_on:
        - database

    database:
      container_name: database
      build: ./postgres/
      restart: always
      image: postgres:latest
      env_file:
        - .env
      ports:
        - 5434:5432